jobs:
  # echo current working directory for each directory
  - name: find-git
    pattern: "^(.*)\\.git$"
    command:
        - sh
        - -c
        - echo "Found git directory! $1"
  - name: find-config
    pattern: "^(.*)\\.(conf|config|cfg)$"
    command:
        - sh
        - -c
        - '>&2 echo "Found $2 file! $1"'